//Action Types
export const INCREMENT_COUNTER = "INCREMENT_COUNTER";
export const DECREMENT_COUNTER = "DECREMENT_COUNTER";
export const SAVE_TEAMS = "SAVE_TEAMS";
export const GET_SINGLE_ROASTER = "GET_SINGLE_ROASTER";
export const GET_PLAYERS = 'GET_PLAYERS';
export const SEARCH_PLAYER_ONE = 'SEARCH_PLAYER_ONE';
export const SEARCH_PLAYER_TWO = 'SEARCH_PLAYER_TWO';
export const SET_LOADING ='SET_LOADING';
export const GET_ALL_PLAYERS_ID ='GET_ALL_PLAYERS_ID ';
